"""add candidate details fields

Revision ID: ac82d94debdb
Revises: 35d9f27b80f0
Create Date: 2026-06-08 12:55:25.051243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac82d94debdb'
down_revision: Union[str, Sequence[str], None] = '35d9f27b80f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all_applications', sa.Column('resume_path', sa.String(), nullable=True))
    op.add_column('all_applications', sa.Column('matched_skills', sa.String(), nullable=True))
    op.add_column('all_applications', sa.Column('missing_skills', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('all_applications', 'missing_skills')
    op.drop_column('all_applications', 'matched_skills')
    op.drop_column('all_applications', 'resume_path')
    # ### end Alembic commands ###
